<?php

declare(strict_types=1);
namespace Avax\Container\Features\Think\Model;

use Avax\Container\Features\Actions\Inject\InjectDependencies;

/**
 * @package Avax\Container\Think\Model
 *
 * Immutable blueprint for method-based dependency injection.
 *
 * MethodPrototype captures the static analysis results for a single method that requires
 * dependency injection. It specifies the method name and the complete parameter
 * specification needed for proper dependency resolution during runtime injection.
 *
 * ARCHITECTURAL ROLE:
 * - Defines injection requirements for constructor and setter methods
 * - Provides parameter specifications for dependency resolution
 * - Enables type-safe method invocation with automatic DI
 * - Supports both constructor and property-setter injection patterns
 *
 * METHOD INJECTION SCENARIOS:
 * ```php
 * // Constructor injection
 * $prototype = new MethodPrototype('__construct', [
 *     new ParameterPrototype('logger', LoggerInterface::class),
 *     new ParameterPrototype('config', Config::class)
 * ]);
 *
 * // Setter injection
 * $prototype = new MethodPrototype('setDatabase', [
 *     new ParameterPrototype('db', DatabaseInterface::class)
 * ]);
 * ```
 *
 * PARAMETER RESOLUTION:
 * Each parameter in the prototype specifies type hints, default values, and nullability
 * constraints that guide the dependency injection process during method invocation.
 *
 * SERIALIZATION SUPPORT:
 * MethodPrototype supports full serialization for caching and compilation scenarios,
 * enabling pre-computed injection prototypes to be stored and reused across requests.
 *
 * PERFORMANCE CHARACTERISTICS:
 * - Immutable design allows safe sharing across resolution operations
 * - Parameter arrays are optimized for sequential access during injection
 * - Memory footprint scales with number of method parameters
 *
 * @see     ParameterPrototype For individual parameter specifications
 * @see     ServicePrototype For complete service injection blueprint
 * @see     InjectDependencies For runtime method injection using MethodPrototype
 * @see docs_md/Features/Think/Model/MethodPrototype.md#quick-summary
 */
readonly class MethodPrototype
{
    /**
     * Creates a new method injection prototype with parameter specifications.
     *
     * Initializes the prototype with the target method name and its complete
     * parameter specification for dependency injection. The parameters define
     * how each method argument should be resolved during runtime injection.
     *
     * PARAMETER ORDERING:
     * Parameters must be specified in the same order as they appear in the
     * method signature to ensure correct argument mapping during injection.
     *
     * DEPENDENCY INJECTION:
     * Each parameter can specify type hints, defaults, and constraints that
     * guide the container's resolution process for that specific argument.
     *
     * @param string               $name       The method name to inject dependencies into
     * @param ParameterPrototype[] $parameters Ordered array of parameter specifications
     * @see docs_md/Features/Think/Model/MethodPrototype.md#method-__construct
     */
    public function __construct(
        public string $name,
        public array  $parameters = []
    ) {}

    /**
     * Deserializes a MethodPrototype from var_export() array format.
     *
     * This magic method enables unserialization from cached or compiled container data.
     * It's automatically called by PHP when loading serialized MethodPrototype instances.
     *
     * USAGE IN COMPILED CONTAINERS:
     * ```php
     * // Generated by compilation
     * $prototype = MethodPrototype::__set_state([
     *     'name' => 'setLogger',
     *     'parameters' => [...]
     * ]);
     * ```
     *
     * @param array $array The serialized array representation
     *
     * @return self The deserialized MethodPrototype instance
     * @see __set_state For PHP's automatic unserialization mechanism
     * @see docs_md/Features/Think/Model/MethodPrototype.md#method-__set_state
     */
    public static function __set_state(array $array) : self
    {
        return self::fromArray(data: $array);
    }

    /**
     * Creates a MethodPrototype instance from an array representation.
     *
     * This factory method reconstructs a MethodPrototype from serialized data, typically
     * loaded from cache or compiled container definitions. It performs validation
     * and type reconstruction for all nested ParameterPrototype objects.
     *
     * ARRAY FORMAT:
     * ```php
     * [
     *     'name' => 'setLogger',
     *     'parameters' => [
     *         ['name' => 'logger', 'type' => 'LoggerInterface', ...],
     *         // ... more parameters
     *     ]
     * ]
     * ```
     *
     * VALIDATION:
     * - Ensures method name is valid string
     * - Reconstructs ParameterPrototype objects from arrays
     * - Maintains parameter ordering for correct injection
     *
     * @param array $data The array containing MethodPrototype data
     *
     * @return self The constructed MethodPrototype instance
     * @throws \InvalidArgumentException If data format is invalid
     * @see docs_md/Features/Think/Model/MethodPrototype.md#method-fromarray
     */
    public static function fromArray(array $data) : self
    {
        return new self(
            name      : $data['name'],
            parameters: array_map(static fn(array $p) : ParameterPrototype => ParameterPrototype::fromArray(data: $p), $data['parameters'] ?? [])
        );
    }

    /**
     * Converts the MethodPrototype to an array representation for serialization.
     *
     * This method enables the MethodPrototype to be serialized for caching or compilation.
     * The resulting array can be stored in files or caches and later reconstructed
     * using fromArray() or __set_state().
     *
     * SERIALIZATION SCENARIOS:
     * - Container compilation for production deployment
     * - Caching analyzed method prototypes to avoid repeated reflection
     * - Persisting injection specifications across application restarts
     *
     * OUTPUT FORMAT:
     * ```php
     * [
     *     'name' => 'setLogger',
     *     'parameters' => [
     *         ['name' => 'logger', 'type' => 'LoggerInterface', ...],
     *         // ... serialized ParameterPrototype arrays
     *     ]
     * ]
     * ```
     *
     * @return array The array representation of this MethodPrototype
     * @see docs_md/Features/Think/Model/MethodPrototype.md#method-toarray
     */
    public function toArray() : array
    {
        return [
            'name'       => $this->name,
            'parameters' => array_map(fn(ParameterPrototype $p) : array => $p->toArray(), $this->parameters),
        ];
    }
}
