<?php

declare(strict_types=1);
namespace Avax\Container\Features\Think\Model;

/**
 * Immutable blueprint for property-based dependency injection.
 *
 * @see docs_md/Features/Think/Model/PropertyPrototype.md#quick-summary
 */
readonly class PropertyPrototype
{
    /**
     * Creates a new property injection prototype with resolution specifications.
     *
     * Initializes the prototype with all the information needed to inject
     * dependencies into this property. The prototype includes type
     * constraints, default values, nullability handling, and required/optional
     * semantics for enterprise-grade dependency injection.
     *
     * PROPERTY ACCESS REQUIREMENTS:
     * - Properties must not be readonly (checked at analysis time)
     * - Private/protected properties require reflection accessibility
     * - Public properties can be injected directly
     *
     * TYPE RESOLUTION PRIORITY:
     * - Class/interface names trigger container resolution
     * - Built-in types require explicit values or defaults
     * - Union types resolved to first compatible type
     *
     * DEFAULT VALUE PRECEDENCE:
     * - Runtime injection overrides take highest priority
     * - Property declaration defaults used as fallback
     * - Container resolution used when no defaults available
     *
     * REQUIRED vs OPTIONAL SEMANTICS:
     * - Required properties must be successfully resolved or throw exception
     * - Optional properties are silently skipped if resolution fails
     * - Required properties enforce dependency contracts at runtime
     * - Optional properties provide graceful degradation
     *
     * @param string      $name       The property name to inject dependencies into
     * @param string|null $type       The type hint (class/interface) for container resolution
     * @param bool        $hasDefault Whether the property has a default value
     * @param mixed       $default    The default value to use if resolution fails
     * @param bool        $allowsNull Whether null is acceptable for this property
     * @param bool        $required   Whether this property must be successfully resolved
     * @see docs_md/Features/Think/Model/PropertyPrototype.md#method-__construct
     */
    public function __construct(
        public string      $name,
        public string|null $type = null,
        public bool        $hasDefault = false,
        public mixed       $default = null,
        public bool        $allowsNull = false,
        public bool        $required = true
    ) {}

    /**
     * Deserializes a PropertyPrototype from var_export() array format.
     *
     * This magic method enables unserialization from cached or compiled container data.
     * It's automatically called by PHP when loading serialized PropertyPrototype instances.
     *
     * USAGE IN COMPILED CONTAINERS:
     * ```php
     * // Generated by compilation
     * $prototype = PropertyPrototype::__set_state([
     *     'name' => 'logger',
     *     'type' => 'LoggerInterface',
     *     'allowsNull' => false,
     *     ...
     * ]);
     * ```
     *
     * @param array $array The serialized array representation
     *
     * @return self The deserialized PropertyPrototype instance
     * @see __set_state For PHP's automatic unserialization mechanism
     * @see docs_md/Features/Think/Model/PropertyPrototype.md#method-__set_state
     */
    public static function __set_state(array $array) : self
    {
        return self::fromArray(data: $array);
    }

    /**
     * Creates a PropertyPrototype instance from an array representation.
     *
     * This factory method reconstructs a PropertyPrototype from serialized data, typically
     * loaded from cache or compiled container definitions. It performs validation
     * and safe type reconstruction for all property prototypes.
     *
     * ARRAY FORMAT:
     * ```php
     * [
     *     'name' => 'logger',
     *     'type' => 'LoggerInterface',
     *     'hasDefault' => false,
     *     'default' => null,
     *     'allowsNull' => false
     * ]
     * ```
     *
     * VALIDATION:
     * - Ensures property name is valid string
     * - Validates type hint format if present
     * - Safely handles default value reconstruction
     * - Maintains nullability flag integrity
     *
     * @param array $data The array containing PropertyPrototype data
     *
     * @return self The constructed PropertyPrototype instance
     * @throws \InvalidArgumentException If data format is invalid
     * @see docs_md/Features/Think/Model/PropertyPrototype.md#method-fromarray
     */
    public static function fromArray(array $data) : self
    {
        return new self(
            name      : $data['name'],
            type      : $data['type'] ?? null,
            hasDefault: $data['hasDefault'] ?? false,
            default   : $data['default'] ?? null,
            allowsNull: $data['allowsNull'] ?? false,
            required  : $data['required'] ?? true
        );
    }

    /**
     * Converts the PropertyPrototype to an array representation for serialization.
     *
     * This method enables the PropertyPrototype to be serialized for caching or compilation.
     * The resulting array can be stored in files or caches and later reconstructed
     * using fromArray() or __set_state().
     *
     * SERIALIZATION SCENARIOS:
     * - Container compilation for production deployment
     * - Caching analyzed property prototypes to avoid repeated reflection
     * - Persisting property metadata across application restarts
     *
     * OUTPUT FORMAT:
     * ```php
     * [
     *     'name' => 'logger',
     *     'type' => 'LoggerInterface',
     *     'hasDefault' => false,
     *     'default' => null,
     *     'allowsNull' => false
     * ]
     * ```
     *
     * @return array The array representation of this PropertyPrototype
     * @see docs_md/Features/Think/Model/PropertyPrototype.md#method-toarray
     */
    public function toArray() : array
    {
        return [
            'name'       => $this->name,
            'type'       => $this->type,
            'hasDefault' => $this->hasDefault,
            'default'    => $this->default,
            'allowsNull' => $this->allowsNull,
            'required'   => $this->required,
        ];
    }
}
